In [1]:
import numpy as np

<b>Array创建数组:</b>

In [2]:
# array()函数，括号内可以是列表，元组，数组，迭代对象，生成器
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [4]:
# 迭代对象
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 生成器
np.array([i**2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
np.array(range(2,11,2))
np.array([i for i in range(10) if i%2==0])

array([0, 2, 4, 6, 8])

In [11]:
np.array([1.1,2.5,3.8,4,5],dtype="int")

array([1, 2, 3, 4, 5])