In [1]:
import numpy as np

In [2]:
ding_list = [1, 2, 3, 4, 5]
ding_list = np.array(ding_list)

In [3]:
ding_list

array([1, 2, 3, 4, 5])

In [4]:
type(ding_list)

numpy.ndarray

In [5]:
ding_list.dtype

dtype('int32')

In [6]:
ding_list.itemsize

4

In [7]:
# 一维
ding_list.shape

(5,)

In [8]:
# 打印总的数字个数
ding_list.size

5

In [9]:
np.size(ding_list)

5

In [10]:
ding_list.ndim

1

In [11]:
# 用某个值全部替换原来的值
ding_list.fill(0)
ding_list

array([0, 0, 0, 0, 0])

In [12]:
ding_list[1:2]

array([0])

In [13]:
ding_list[1:4]

array([0, 0, 0])

对于ndarray结构来说，里面所有的元素必须是同一类型的，如果不是，会自动向下进行转换