In [2]:
import numpy as np
# 矩阵格式，多维度
ding_list = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
ding_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
ding_list.shape

(3, 3)

In [5]:
ding_list.size

9

In [6]:
ding_list.ndim

2

In [7]:
ding_list[1, 1]

5

In [8]:
ding_list[1]

array([4, 5, 6])

In [9]:
ding_list[:, 1]

array([2, 5, 8])

In [10]:
# 左闭右开的区间
ding_list = np.arange(0, 100, 10)

In [11]:
ding_list

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
random_array = np.random.rand(10)
random_array

array([0.54500819, 0.00565765, 0.66009864, 0.36717456, 0.2192677 ,
       0.71065017, 0.18348379, 0.35613495, 0.01210505, 0.00422904])

In [14]:
mask = random_array > 0.5

In [15]:
mask

array([ True, False,  True, False, False,  True, False, False, False,
       False])

In [16]:
ding_list[mask]

array([ 0, 20, 50])

In [17]:
ding_list = np.array([10, 20, 30, 40, 50])
ding_list > 30

array([False, False, False,  True,  True])

In [18]:
# 返回满足条件的索引值
np.where(ding_list > 30)

(array([3, 4], dtype=int64),)