In [1]:
import numpy as np

In [2]:
ding_array = np.array([[1, 2, 3], [4, 5, 6]])
ding_array

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# 求和
# 1+2+3+4+5+6
np.sum(ding_array)

21

指定要进行的操作是沿着什么轴(维度)

In [4]:
# 按照维度进行求和
np.sum(ding_array, axis=0)


array([5, 7, 9])

In [5]:
np.sum(ding_array, axis=1)

array([ 6, 15])

In [6]:
# 按照最后一个轴进行相加
np.sum(ding_array, axis=-1)

array([ 6, 15])

In [7]:
# 1*2*3*4*5*6
ding_array.prod()

720

In [9]:
ding_array.prod(axis=0)

array([ 4, 10, 18])

In [11]:
ding_array.prod(axis=1)

array([  6, 120])

In [13]:
# 全局的最小值
ding_array.min()

1

In [14]:
ding_array.min(axis=0)

array([1, 2, 3])

In [15]:
ding_array.min(axis=1)

array([1, 4])

In [16]:
ding_array.argmin()

0

In [17]:
ding_array.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [18]:
ding_array.argmin(axis=1)

array([0, 0], dtype=int64)

In [19]:
ding_array.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [20]:
ding_array.argmax()

5

In [21]:
ding_array.mean()

3.5

In [22]:
ding_array.mean(axis=0)

array([2.5, 3.5, 4.5])

In [23]:
ding_array.mean(axis=1)

array([2., 5.])

In [24]:
# 小于2的值都为2，大于4的值都为4
ding_array.clip(2, 4)

array([[2, 2, 3],
       [4, 4, 4]])