In [1]:
import numpy as np

In [2]:
ding_array = np.array([[1.5, 1.3, 7.5], [5.6, 7.8, 1.2]])
ding_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [4]:
np.sort(ding_array, axis=1)

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [5]:
ding_array = np.linspace(0, 10, 10)

In [6]:
ding_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [8]:
values = np.array([2.5, 6.5, 9.5])

In [9]:
# 查找应该插入到的位置，必须是排序好的数组才能用serachsorted
np.searchsorted(ding_array, values)

array([3, 6, 9], dtype=int64)

In [2]:
ding_array = np.array([[1, 0, 6], [2, 3, 1], [2, 4, 0]])
ding_array

array([[1, 0, 6],
       [2, 3, 1],
       [2, 4, 0]])