In [1]:
import numpy as np

对数组形状进行操作

In [2]:
ding_array = np.arange(10)

In [3]:
ding_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ding_array.shape

(10,)

In [5]:
ding_array.shape = 2, 5

In [6]:
ding_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
ding_array = np.arange(10)
ding_array.shape

(10,)

In [8]:
ding_array = ding_array[np.newaxis, :]
ding_array.shape

(1, 10)

In [9]:
ding_array = np.arange(10)
ding_array = ding_array[:, np.newaxis]
ding_array.shape

(10, 1)

In [10]:
ding_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
ding_array = ding_array[:, :, np.newaxis, np.newaxis]
ding_array.shape

(10, 1, 1, 1)

In [12]:
# 将空的轴去掉
ding_array = ding_array.squeeze()
ding_array.shape

(10,)

In [13]:
# 数组的连接
a = np.array([[123, 456, 678], [3214, 456, 134]])
b = np.array([[1235, 3124, 432], [43, 13, 134]])

In [15]:
c = np.concatenate((a, b), axis=1)
c

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [16]:
np.vstack((a, b))

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [17]:
np.column_stack((a, b))

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [18]:
a.flatten() # 拉平

array([ 123,  456,  678, 3214,  456,  134])

In [19]:
a.ravel()   # 拉平

array([ 123,  456,  678, 3214,  456,  134])